### ISSUE TITLE
Request for model weight.

### ISSUE THREAD

**Issue by JH-GEECS** [VL-Group/PENET#1]
Hello,

I am a researcher who is interested in your deep learning model. I have read your paper and I am impressed by the results you have achieved. I would like to reproduce your experiments and compare them with other methods.

However, I noticed that you did not provide the weight of your model in your github repository. I understand that you may have some reasons to keep it private, but I would appreciate it if you could share it with me for research purposes only.

I hope you do not mind my request and I respect your decision. I think your work is very valuable and I would like to learn more from it. Thank you for your time and attention.

Sincerely,
Jiho Choi

**Comment by aa200647963** [comment]
We have provided the model's weights and log files in the README.
