### ISSUE TITLE
运行train.sh时的报错“KeyError: 'PrototypeEmbeddingNetwork”

### ISSUE THREAD

**Issue by 1XU-WANG** [VL-Group/PENET#8]
![image](https://github.com/VL-Group/PENET/assets/82601665/826355d5-12bd-4fb2-90f8-3ebdffac3ce0)
运行train.sh时的错误，不知道是啥原因（本人菜鸡刚刚接触SGG）

**Comment by aa200647963** [comment]
你这是没用到我的代码... 这个的意思是没有定义PrototypeEmbeddingNetwork这个类

**Comment by 1XU-WANG** [comment]
![image](https://github.com/VL-Group/PENET/assets/82601665/c74f9110-5a30-42b1-9c69-6396753db53a)
啊，不会吧，我按步骤来的呀

**Comment by CL2LC** [comment]
您好，请问您这个问题怎么解决的呀
