### ISSUE TITLE
Regarding t-sne visualization in Figure 4.

### ISSUE THREAD

**Issue by KanghoonYoon** [VL-Group/PENET#9]
Hi, Thanks for sharing great work.

I would like to ask the embedding used for the t-sne algorithm.

As I understand, the final output of the relation representation (rel_rep_norm) has 4096 dim.

Did you use the relation rep directly to visualize the t-sne ?
or did you use any pre-processing or other representations?

Best, Kanghoon Yoon

**Comment by aa200647963** [comment]
I use PCA for dimensionality reduction and then t-sne for visualization

**Comment by missyoudaisy** [comment]
> I use PCA for dimensionality reduction and then t-sne for visualization

你好，PCA和t-sne都有降维的作用，使用PCA是先将特征降到几维呢？2维吗？
然后直接使用t-sne可视化？
期待得到您的回复，谢谢！：）

**Comment by aa200647963** [comment]
降低到2维，然后使用了t-sne可视化

**Comment by missyoudaisy** [comment]
> 降低到2维，然后使用了t-sne可视化

谢谢！:)

**Comment by KanghoonYoon** [comment]
Thanks for replying ,I will close my issue!
